# Generated by Django 4.2.7 on 2025-12-23 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaExterna',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_orden', models.CharField(max_length=20, unique=True, verbose_name='Número de Orden')),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('en_transito', 'En Tránsito'), ('completada', 'Completada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=20, verbose_name='Estado')),
                ('motivo', models.TextField(verbose_name='Motivo de la transferencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad')),
                ('pdf_generado', models.BooleanField(default=False, verbose_name='PDF Generado')),
                ('qr_token', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Token QR')),
                ('url_firmada', models.TextField(blank=True, null=True, verbose_name='URL Firmada')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='ordenes_traspaso/', verbose_name='Archivo PDF')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('fecha_inicio_transito', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio de Tránsito')),
                ('fecha_completada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completación')),
                ('firma_origen', models.JSONField(blank=True, help_text='Timestamp y usuario que confirma salida', null=True, verbose_name='Firma Digital Origen')),
                ('firma_destino', models.JSONField(blank=True, help_text='Timestamp y usuario que confirma recepción', null=True, verbose_name='Firma Digital Destino')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('acueducto_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada', to='core.acueducto', verbose_name='Acueducto Destino')),
                ('acueducto_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salida', to='core.acueducto', verbose_name='Acueducto Origen')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('hidrologica_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada', to='core.hidrologica', verbose_name='Hidrológica Destino')),
                ('hidrologica_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salida', to='core.hidrologica', verbose_name='Hidrológica Origen')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Transferencia Externa',
                'verbose_name_plural': 'Transferencias Externas',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInterno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.TextField(verbose_name='Motivo del movimiento')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Movimiento')),
                ('acueducto_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_entrada', to='core.acueducto', verbose_name='Acueducto Destino')),
                ('acueducto_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_salida', to='core.acueducto', verbose_name='Acueducto Origen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_internos', to='inventory.iteminventario', verbose_name='Ítem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento Interno',
                'verbose_name_plural': 'Movimientos Internos',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='ItemTransferencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='inventory.iteminventario')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_transferencia', to='transfers.transferenciaexterna')),
            ],
            options={
                'verbose_name': 'Ítem de Transferencia',
                'verbose_name_plural': 'Ítems de Transferencia',
            },
        ),
        migrations.AddIndex(
            model_name='transferenciaexterna',
            index=models.Index(fields=['estado', 'fecha_solicitud'], name='transfers_t_estado_00b0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='transferenciaexterna',
            index=models.Index(fields=['hidrologica_origen', 'estado'], name='transfers_t_hidrolo_d546d0_idx'),
        ),
        migrations.AddIndex(
            model_name='transferenciaexterna',
            index=models.Index(fields=['hidrologica_destino', 'estado'], name='transfers_t_hidrolo_ba4fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='transferenciaexterna',
            index=models.Index(fields=['qr_token'], name='transfers_t_qr_toke_0d3208_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientointerno',
            index=models.Index(fields=['item', 'fecha_movimiento'], name='transfers_m_item_id_1c7b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientointerno',
            index=models.Index(fields=['acueducto_origen', 'fecha_movimiento'], name='transfers_m_acueduc_0c0f80_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientointerno',
            index=models.Index(fields=['acueducto_destino', 'fecha_movimiento'], name='transfers_m_acueduc_68d4d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemtransferencia',
            unique_together={('transferencia', 'item')},
        ),
    ]
