# Generated by Django 4.2.7 on 2025-12-23 04:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_item', models.CharField(choices=[('tuberia', 'Tubería'), ('motor', 'Motor'), ('valvula', 'Válvula'), ('quimico', 'Químico')], max_length=20, verbose_name='Tipo de Ítem')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Categoría de Ítem',
                'verbose_name_plural': 'Categorías de Ítems',
                'ordering': ['tipo_item', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('tipo', models.CharField(choices=[('tuberia', 'Tubería'), ('motor', 'Motor'), ('valvula', 'Válvula'), ('quimico', 'Químico')], max_length=20, verbose_name='Tipo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_transito', 'En Tránsito'), ('asignado', 'Asignado'), ('mantenimiento', 'En Mantenimiento'), ('dado_baja', 'Dado de Baja')], default='disponible', max_length=20, verbose_name='Estado')),
                ('historial_movimientos', models.JSONField(default=list, help_text='Ficha de vida completa del ítem', verbose_name='Historial de Movimientos')),
                ('especificaciones', models.JSONField(blank=True, default=dict, help_text='Características técnicas específicas del ítem', verbose_name='Especificaciones Técnicas')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Unitario')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisición')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('numero_factura', models.CharField(blank=True, max_length=50, verbose_name='Número de Factura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('acueducto_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_inventario', to='core.acueducto', verbose_name='Acueducto Actual')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.categoriaitem', verbose_name='Categoría')),
                ('hidrologica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_inventario', to='core.hidrologica', verbose_name='Hidrológica')),
            ],
            options={
                'verbose_name': 'Ítem de Inventario',
                'verbose_name_plural': 'Ítems de Inventario',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hidrologica', 'tipo'], name='inventory_i_hidrolo_9007ea_idx'), models.Index(fields=['hidrologica', 'estado'], name='inventory_i_hidrolo_a7cdc7_idx'), models.Index(fields=['sku'], name='inventory_i_sku_566de5_idx'), models.Index(fields=['acueducto_actual'], name='inventory_i_acueduc_77495f_idx')],
            },
        ),
    ]
