# Generated by Django 4.2.7 on 2025-12-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventario',
            name='historial_movimientos',
            field=models.JSONField(blank=True, default=list, help_text='Ficha de vida completa del ítem', verbose_name='Historial de Movimientos'),
        ),
    ]
