# Generated by Django 4.2.7 on 2025-12-23 04:01

import apps.notifications.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('nueva_solicitud', 'Nueva Solicitud de Transferencia'), ('transferencia_aprobada', 'Transferencia Aprobada'), ('transferencia_rechazada', 'Transferencia Rechazada'), ('transferencia_en_transito', 'Transferencia en Tránsito'), ('transferencia_completada', 'Transferencia Completada'), ('movimiento_interno', 'Movimiento Interno Realizado'), ('item_estado_cambiado', 'Estado de Ítem Cambiado'), ('sistema', 'Notificación del Sistema')], max_length=30, unique=True, verbose_name='Tipo')),
                ('titulo_template', models.CharField(help_text='Usar {variable} para variables dinámicas', max_length=200, verbose_name='Plantilla de Título')),
                ('mensaje_template', models.TextField(help_text='Usar {variable} para variables dinámicas', verbose_name='Plantilla de Mensaje')),
                ('prioridad_default', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad por Defecto')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificación',
            },
        ),
        migrations.CreateModel(
            name='CanalNotificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_habilitado', models.BooleanField(default=True, verbose_name='Email Habilitado')),
                ('push_habilitado', models.BooleanField(default=True, verbose_name='Push Habilitado')),
                ('tipos_habilitados', models.JSONField(default=list, help_text='Lista de tipos de notificaciones habilitadas para este usuario', verbose_name='Tipos Habilitados')),
                ('horario_inicio', models.TimeField(default='08:00', help_text='Hora de inicio para recibir notificaciones', verbose_name='Horario de Inicio')),
                ('horario_fin', models.TimeField(default='18:00', help_text='Hora de fin para recibir notificaciones', verbose_name='Horario de Fin')),
                ('dias_habilitados', models.JSONField(default=apps.notifications.models.default_dias_habilitados, help_text='Lista de días de la semana habilitados (0=Lunes, 6=Domingo)', verbose_name='Días Habilitados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canal_notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Canal de Notificación',
                'verbose_name_plural': 'Canales de Notificación',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('nueva_solicitud', 'Nueva Solicitud de Transferencia'), ('transferencia_aprobada', 'Transferencia Aprobada'), ('transferencia_rechazada', 'Transferencia Rechazada'), ('transferencia_en_transito', 'Transferencia en Tránsito'), ('transferencia_completada', 'Transferencia Completada'), ('movimiento_interno', 'Movimiento Interno Realizado'), ('item_estado_cambiado', 'Estado de Ítem Cambiado'), ('sistema', 'Notificación del Sistema')], max_length=30, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad')),
                ('datos_adicionales', models.JSONField(blank=True, default=dict, help_text='Información adicional como IDs de transferencias, ítems, etc.', verbose_name='Datos Adicionales')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificatio_usuario_8e0ccb_idx'), models.Index(fields=['usuario', 'tipo'], name='notificatio_usuario_41297a_idx'), models.Index(fields=['created_at'], name='notificatio_created_f8f3c4_idx'), models.Index(fields=['expires_at'], name='notificatio_expires_57298d_idx')],
            },
        ),
    ]
